version: '3.8'

services:
  db:
    image: postgres:alpine
    volumes:
      - ~/docker/volumes/dsacancellation/db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # server:
  #   build: ./
  #   image: digitalplug/dsacancellationbot
  #   ports:
  #     - 8000:8000
  #     - 5900:5900
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   environment:
  #     - NODE_ENV=docker
  #   env_file:
  #     - .env
  #   networks:
  #     - default

networks:
  default:
    external:
      name: sample
